# Generated by Django 3.1.5 on 2023-01-26 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0019_auto_20230115_1452'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeruser',
            name='emp_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ชื่อผู้จ้าง'),
        ),
        migrations.AlterField(
            model_name='employeruser',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ที่ตั้ง'),
        ),
        migrations.AlterField(
            model_name='employeruser',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='เบอร์โทร'),
        ),
        migrations.AlterField(
            model_name='jobberuser',
            name='age',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='อายุ'),
        ),
        migrations.AlterField(
            model_name='jobberuser',
            name='education',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.education', verbose_name='ระดับการศึกษา'),
        ),
        migrations.AlterField(
            model_name='jobberuser',
            name='gender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.gender'),
        ),
    ]
