# Generated by Django 3.1.5 on 2023-01-26 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0019_auto_20230115_1452'),
        ('users', '0002_auto_20230126_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobberuser',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.province', verbose_name='จังหวัด'),
        ),
    ]
