# Generated by Django 3.1.5 on 2023-01-29 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0019_auto_20230115_1452'),
        ('users', '0006_adminuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ชื่องาน')),
                ('description', models.TextField(blank=True, verbose_name='รายละเอียดงาน')),
                ('location', models.CharField(max_length=100, verbose_name='ที่ตั้ง')),
                ('phone', models.CharField(max_length=100, verbose_name='เบอร์โทร')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('emp_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.employeruser', verbose_name='ผู้จ้างงาน')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.gender', verbose_name='เพศ')),
                ('jobber', models.ManyToManyField(blank=True, to='users.JobberUser')),
                ('pay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.pay', verbose_name='ค่าตอบแทน')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.province', verbose_name='จังหวัด')),
            ],
        ),
    ]
