# Generated by Django 3.1.5 on 2023-01-29 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_jobuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobuser',
            name='picture',
            field=models.FileField(blank=True, null=True, upload_to='jobs/static/jobs/images/Job/', verbose_name='รูปภาพ'),
        ),
    ]
