# Generated by Django 3.1.5 on 2023-01-31 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20230130_0046'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeruser',
            name='check',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobberuser',
            name='check',
            field=models.BooleanField(default=False),
        ),
    ]
