# Generated by Django 3.1.5 on 2023-01-31 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0019_auto_20230115_1452'),
        ('users', '0011_auto_20230201_0032'),
    ]

    operations = [
        migrations.AddField(
            model_name='employercheck',
            name='age',
            field=models.IntegerField(default=0, null=True, verbose_name='อายุ'),
        ),
        migrations.AddField(
            model_name='employercheck',
            name='gender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.gender', verbose_name='เพศ'),
        ),
        migrations.AddField(
            model_name='jobbercheck',
            name='age',
            field=models.IntegerField(default=0, null=True, verbose_name='อายุ'),
        ),
        migrations.AddField(
            model_name='jobbercheck',
            name='gender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.gender', verbose_name='เพศ'),
        ),
    ]
