# Generated by Django 3.1.5 on 2023-01-31 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20230201_0305'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobberuser',
            name='birthdate',
            field=models.DateField(blank=True, null=True, verbose_name='วันเกิด'),
        ),
    ]
