# Generated by Django 3.1.5 on 2023-01-31 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_jobberuser_birthdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobberuser',
            name='birthdate',
        ),
    ]
