# Generated by Django 3.1.5 on 2023-01-31 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0019_auto_20230115_1452'),
        ('users', '0014_remove_jobberuser_birthdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employercheck',
            name='gender',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.gender', verbose_name='เพศ'),
        ),
        migrations.AlterField(
            model_name='jobbercheck',
            name='gender',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.gender', verbose_name='เพศ'),
        ),
    ]
