# Generated by Django 3.1.5 on 2023-02-02 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20230201_0357'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplyJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apply_date', models.DateField(auto_now_add=True)),
                ('emp_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.employeruser', verbose_name='ผู้จ้างงาน')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.jobuser', verbose_name='ชื่องาน')),
                ('jobber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.jobberuser', verbose_name='ผู้สมัคร')),
            ],
        ),
    ]
