# Generated by Django 3.1.5 on 2023-02-02 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_applyjob_check_apply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyjob',
            name='apply_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='วันที่สมัคร'),
        ),
        migrations.AlterField(
            model_name='applyjob',
            name='check_apply',
            field=models.BooleanField(default=False, verbose_name='จ้างงาน'),
        ),
    ]
