# Generated by Django 3.1.5 on 2023-02-02 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20230202_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyjob',
            name='picture',
            field=models.FileField(blank=True, null=True, upload_to='jobs/static/jobs/images/ApplyJob/', verbose_name='รูปภาพ'),
        ),
    ]
