# Generated by Django 3.1.5 on 2023-02-02 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0020_employersubjectcomplain_jobbersubjectcomplain'),
        ('users', '0021_applyjob_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobberComplain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=256, verbose_name='รายละเอียดงาน')),
                ('complain_date', models.DateTimeField(auto_now_add=True, verbose_name='วันที่ร้องเรียน')),
                ('status', models.BooleanField(default=False, verbose_name='ได้รับคำร้อง')),
                ('emp_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.employeruser', verbose_name='ผู้จ้างงาน')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.jobuser', verbose_name='ชื่องาน')),
                ('jobber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.jobberuser', verbose_name='ผู้สมัคร')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.jobbersubjectcomplain', verbose_name='หัวข้อร้องเรียน')),
            ],
        ),
        migrations.CreateModel(
            name='EmployerComplain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=256, verbose_name='รายละเอียดงาน')),
                ('complain_date', models.DateTimeField(auto_now_add=True, verbose_name='วันที่ร้องเรียน')),
                ('status', models.BooleanField(default=False, verbose_name='ได้รับคำร้อง')),
                ('emp_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.employeruser', verbose_name='ผู้จ้างงาน')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.jobuser', verbose_name='ชื่องาน')),
                ('jobber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.jobberuser', verbose_name='ผู้สมัคร')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.jobbersubjectcomplain', verbose_name='หัวข้อร้องเรียน')),
            ],
        ),
    ]
