# Generated by Django 3.1.5 on 2023-02-02 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0020_employersubjectcomplain_jobbersubjectcomplain'),
        ('users', '0022_employercomplain_jobbercomplain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employercomplain',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.employersubjectcomplain', verbose_name='หัวข้อร้องเรียน'),
        ),
    ]
