# Generated by Django 3.1.5 on 2023-02-04 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_auto_20230204_1735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employercheck',
            name='gender',
        ),
    ]
