# Generated by Django 3.1.5 on 2023-02-04 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_remove_employercheck_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='jobber',
        ),
        migrations.AddField(
            model_name='job',
            name='jobber',
            field=models.IntegerField(default=0, verbose_name='จำนวนผู้สมัคร'),
        ),
    ]
