# Generated by Django 3.1.5 on 2023-02-04 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_auto_20230205_0405'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='apply',
            field=models.BooleanField(default=False, verbose_name='มีการจ้างงาน'),
        ),
    ]
