# Generated by Django 3.1.5 on 2023-02-07 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_remove_jobbercheck_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeruser',
            name='hasjobber',
            field=models.BooleanField(default=False, verbose_name='มีลูกจ้าง'),
        ),
    ]
