# Generated by Django 3.1.5 on 2023-01-14 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('emp_name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=100, verbose_name='Email')),
                ('phone', models.CharField(max_length=100, verbose_name='Phone')),
                ('address', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('pic', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('lat', models.FloatField(max_length=100)),
                ('long', models.FloatField(max_length=100)),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.province')),
            ],
        ),
        migrations.CreateModel(
            name='Jobber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=100, verbose_name='Email')),
                ('phone', models.CharField(max_length=100, verbose_name='Phone')),
                ('address', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('age', models.IntegerField(default=0)),
                ('pic', models.CharField(max_length=100)),
                ('education', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.education')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.gender')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.province')),
                ('score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.score')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('emp_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.employer')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.gender')),
                ('pay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.pay')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.province')),
            ],
        ),
        migrations.AddField(
            model_name='employer',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.province'),
        ),
        migrations.AddField(
            model_name='employer',
            name='score',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.score'),
        ),
    ]
