# Generated by Django 3.1.5 on 2023-01-14 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20230115_0039'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='pay',
            new_name='score',
        ),
        migrations.AlterField(
            model_name='jobber',
            name='score',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.score'),
        ),
    ]
