# Generated by Django 3.1.5 on 2023-01-14 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_auto_20230115_0103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer',
            name='pic',
        ),
        migrations.RemoveField(
            model_name='jobber',
            name='pic',
        ),
        migrations.AddField(
            model_name='employer',
            name='picture',
            field=models.FileField(blank=True, null=True, upload_to='jobs/static/images/'),
        ),
        migrations.AddField(
            model_name='jobber',
            name='picture',
            field=models.FileField(blank=True, null=True, upload_to='jobs/static/images/'),
        ),
    ]
