# Generated by Django 3.1.5 on 2023-01-14 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_auto_20230115_0126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='emp_name',
        ),
        migrations.DeleteModel(
            name='Employer',
        ),
    ]
