# Generated by Django 3.1.5 on 2023-01-14 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_auto_20230115_0132'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('emp_name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=100, verbose_name='Email')),
                ('phone', models.CharField(max_length=100, verbose_name='Phone')),
                ('address', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('picture', models.FileField(blank=True, null=True, upload_to='jobs/static/่jobs/images/Emp/')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.province')),
            ],
        ),
        migrations.RemoveField(
            model_name='job',
            name='jobber_score',
        ),
        migrations.RemoveField(
            model_name='jobber',
            name='applied_job',
        ),
        migrations.RemoveField(
            model_name='jobber',
            name='qrcode',
        ),
        migrations.RemoveField(
            model_name='jobber',
            name='score',
        ),
        migrations.AlterField(
            model_name='jobber',
            name='picture',
            field=models.FileField(blank=True, null=True, upload_to='jobs/static/่jobs/images/Jobber/'),
        ),
        migrations.DeleteModel(
            name='Score',
        ),
        migrations.AddField(
            model_name='job',
            name='emp_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.employer'),
        ),
    ]
