# Generated by Django 3.1.5 on 2023-01-14 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_auto_20230115_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='picture',
            field=models.FileField(blank=True, null=True, upload_to='jobs/static/images/'),
        ),
        migrations.AlterField(
            model_name='jobber',
            name='picture',
            field=models.FileField(blank=True, null=True, upload_to='jobs/static/images/'),
        ),
    ]
