# Generated by Django 3.1.5 on 2023-01-14 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_auto_20230115_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='picture',
            field=models.FileField(blank=True, null=True, upload_to='jobs/static/jobs/images/Employer/'),
        ),
        migrations.AlterField(
            model_name='jobber',
            name='picture',
            field=models.FileField(blank=True, null=True, upload_to='jobs/static/jobs/images/Jobber/'),
        ),
    ]
