# Generated by Django 3.1.5 on 2023-01-14 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0013_auto_20230115_0156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobber',
            old_name='Email',
            new_name='email',
        ),
        migrations.RemoveField(
            model_name='employer',
            name='Email',
        ),
        migrations.AddField(
            model_name='employer',
            name='email',
            field=models.EmailField(default=1, max_length=100, verbose_name='อีเมล'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employer',
            name='emp_name',
            field=models.CharField(max_length=100, verbose_name='ชื่อ-สกุล'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='name',
            field=models.CharField(max_length=100, verbose_name='ชื่อองค์กร/ร้านค้า'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='phone',
            field=models.CharField(max_length=100, verbose_name='เบอร์โทร'),
        ),
    ]
