# Generated by Django 3.1.5 on 2023-01-14 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0014_auto_20230115_0207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='description',
        ),
        migrations.AlterField(
            model_name='education',
            name='education',
            field=models.CharField(max_length=100, verbose_name='ระดับการศึกษา'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='address',
            field=models.CharField(max_length=100, verbose_name='ที่อยู่'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='emp_name',
            field=models.CharField(max_length=100, verbose_name='ชื่อผู้จ้าง'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='location',
            field=models.CharField(max_length=100, verbose_name='ที่ตั้ง'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='picture',
            field=models.FileField(blank=True, null=True, upload_to='jobs/static/jobs/images/Employer/', verbose_name='รูปภาพ'),
        ),
        migrations.AlterField(
            model_name='gender',
            name='gender',
            field=models.CharField(max_length=100, verbose_name='เพศ'),
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(blank=True, verbose_name='รายละเอียดงาน'),
        ),
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(max_length=100, verbose_name='ที่ตั้ง'),
        ),
        migrations.AlterField(
            model_name='job',
            name='name',
            field=models.CharField(max_length=100, verbose_name='ชื่องาน'),
        ),
        migrations.AlterField(
            model_name='job',
            name='phone',
            field=models.CharField(max_length=100, verbose_name='เบอร์โทร'),
        ),
        migrations.AlterField(
            model_name='jobber',
            name='address',
            field=models.CharField(max_length=100, verbose_name='ที่อยู่'),
        ),
        migrations.AlterField(
            model_name='jobber',
            name='email',
            field=models.EmailField(max_length=100, verbose_name='อีเมล'),
        ),
        migrations.AlterField(
            model_name='jobber',
            name='location',
            field=models.CharField(max_length=100, verbose_name='ที่ตั้ง'),
        ),
        migrations.AlterField(
            model_name='jobber',
            name='name',
            field=models.CharField(max_length=100, verbose_name='ชื่อ-สกุล'),
        ),
        migrations.AlterField(
            model_name='jobber',
            name='phone',
            field=models.CharField(max_length=100, verbose_name='เบอร์โทร'),
        ),
        migrations.AlterField(
            model_name='jobber',
            name='picture',
            field=models.FileField(blank=True, null=True, upload_to='jobs/static/jobs/images/Jobber/', verbose_name='รูปภาพ'),
        ),
        migrations.AlterField(
            model_name='location',
            name='lat',
            field=models.FloatField(max_length=100, verbose_name='ละติจูด'),
        ),
        migrations.AlterField(
            model_name='location',
            name='long',
            field=models.FloatField(max_length=100, verbose_name='ลองติจูด'),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=100, verbose_name='ที่ตั้ง'),
        ),
        migrations.AlterField(
            model_name='pay',
            name='pay',
            field=models.CharField(max_length=100, verbose_name='ค่าตอบแทน'),
        ),
        migrations.AlterField(
            model_name='province',
            name='province',
            field=models.CharField(max_length=100, verbose_name='จังหวัด'),
        ),
    ]
