# Generated by Django 3.1.5 on 2023-01-14 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0015_auto_20230115_0215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobber',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ที่อยู่'),
        ),
        migrations.AlterField(
            model_name='jobber',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ที่ตั้ง'),
        ),
    ]
