# Generated by Django 3.1.5 on 2023-01-15 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0018_auto_20230115_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='emp_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.employer', verbose_name='ผู้จ้างงาน'),
        ),
        migrations.AlterField(
            model_name='job',
            name='gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.gender', verbose_name='เพศ'),
        ),
        migrations.AlterField(
            model_name='job',
            name='pay',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.pay', verbose_name='ค่าตอบแทน'),
        ),
        migrations.AlterField(
            model_name='job',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.province', verbose_name='จังหวัด'),
        ),
        migrations.AlterField(
            model_name='jobber',
            name='education',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.education', verbose_name='ระดับการศึกษา'),
        ),
        migrations.AlterField(
            model_name='location',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.province', verbose_name='จังหวัด'),
        ),
    ]
