# Generated by Django 3.1.5 on 2023-02-02 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0019_auto_20230115_1452'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployerSubjectComplain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100, verbose_name='หัวข้อร้องเรียน')),
            ],
        ),
        migrations.CreateModel(
            name='JobberSubjectComplain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100, verbose_name='หัวข้อร้องเรียน')),
            ],
        ),
    ]
